### ISSUE TITLE
single screen option in 0.5?

### ISSUE THREAD

**Issue by Ninoh-FOX** [Drenn1/GameYob#150]
I saw that the last code copile a nds with single screen option, but this version is very unstable.  
How I can insert the single screen option in 0.5 code?
Thaks (is for a nds with only a screen "gba macro")

**Comment by Drenn1** [comment]
Yeah, the current code state is a big mess of unfinished and broken features. You could try one of the earliest builds with single-screen mode, but even at that point it looks like some overhauls had been made since v0.5.

You could try commit 9e9764eb915581fc736dbce0cdd93df2032cfd4d.

**Comment by Ninoh-FOX** [comment]
Thanks, i can compile the last code for git, but the original code from 0.5 show me error in make amr9.... :(

**Comment by Drenn1** [comment]
This is in the latest release now.
