### ISSUE TITLE
i know this sounds stupid

### ISSUE THREAD

**Issue by nikolaifryman** [Drenn1/GameYob#159]
i can't find the 3dsx file?

**Comment by Drenn1** [comment]
This is for GameYob DS. The download for that included a CIA, which may have led you to believe it was a 3DS app, but the CIA is actually DSiWare.

You can search for "GameYob 3DS" to use that, but the DS version actually has some advantages over the 3DS one (speed, mostly).

**Comment by nikolaifryman** [comment]
oh thanks
