### ISSUE TITLE
Missing .ini file?

### ISSUE THREAD

**Issue by garath77** [Drenn1/GameYob#160]
Downloaded 32515_gameyob.zip via Emuparadise. Unzipped straight to my R4i card in root, ran and got error 'no file found'. Checked FAQ, saw mention of an INI file, but when I looked at the files on my R4i, nothing was there. Also nothing but the gameyobds.nds file in the ZIP file I downloaded. I pulled the newest file from the link via GitHub as well, no INI file in that either. How can I make this work?

**Comment by Drenn1** [comment]
Gameyob doesn't need any extra files to run. The ini only stores values after they're changed. I've never heard of this error. Can you confirm that other homebrew works? It might be an issue with your flashcard.

**Comment by garath77** [comment]
I'll try it again tonight with a fresh copy of my R4i card and one game. Maybe I did something wrong...

**Comment by garath77** [comment]
And it worked as advertised with a fresh copy on a clean card. Maybe it was conflicting with something else that was on the card before. Closing
