### ISSUE TITLE
GameYob does not open on HBL 11.5

### ISSUE THREAD

**Issue by Bas25** [Drenn1/GameYob#162]
Every time I try open GameYob on my Homebrewed old 3ds I get a yellow screen. Is there a solution for this?

**Comment by Drenn1** [comment]
Dunno, but for the 3ds version you should go here: https://github.com/Steveice10/GameYob/issues

Though that's not so active, either. If you don't have any luck with that, it may be worth trying the ds version as dsiware (it's better in some ways, worse in others).
