### ISSUE TITLE
Super Mario Land 2 stuttering

### ISSUE THREAD

**Issue by TaDog321** [Drenn1/GameYob#167]
While playing SML2 via GameYob, the emulator stutters at about 3-second intervals during gameplay. I tried the game using 0.5.1 and 0.5.2 and it hasn't made a difference.

**Comment by Drenn1** [comment]
Did you try turning off autosaving?

**Comment by TaDog321** [comment]
No, I haven't. That however fixed the issue (thank you). But how would I go about saving progress I made?

**Comment by Drenn1** [comment]
You just need to select "exit" to return to the rom selection menu before turning off the ds; this copies the save to the SD card. Also, I think the "X" button is mapped to copy the save as well, though I don't normally use that.
