### ISSUE TITLE
Window internal line counter not tracked independently of LY

### ISSUE THREAD

**Issue by tbsp** [Drenn1/GameYob#188]
As described here: https://gbdev.io/pandocs/Tile_Maps.html?highlight=window#window

This results in significant graphical glitches in games which disable the Window mid-frame and re-enable it afterward (https://tbsp.itch.io/shock-lobster), depending on the line advancement to cease while the Window is disabled.

**Comment by tbsp** [comment]
Correction: It was being tracked independently, it was just incorrectly incrementing even if the Window was disabled.

**Comment by Drenn1** [comment]
As you can probably tell, this project is a bit dead. But, I appreciate the fix so I'll merge it. First though, could you give me an example of a game that this fixes?

**Comment by tbsp** [comment]
Yeah, I figured it was a long shot but figured it wouldn't hurt to submit a PR anyways. I see you found my mention of Shock Lobster. It wouldn't be too had to adjust the WX value every time I disable the Window to work around the bug as well, but there may be other games that benefit from the fix.
