### ISSUE TITLE
Feature request: (Wireless) Link cable emulation

### ISSUE THREAD

**Issue by etking** [Drenn1/GameYob#65]
Don't know if this is technically possible with the current DS devtools but it would be a nice to have feature for sure, allowing to enjoy real wireless multiplayer.

**Comment by Farhan1379** [comment]
I also had try using Wireless Multiplay using Gameyob using my DSi (Twilight Menu ++) and DS Lite (R4 Cartridge) but, it says "Warining: Link Emulation Sucks.", But it works on some of Gameboy Games like Dr. Mario and TETRIS but its Not Work in Gameboy Color Games Like Super Mario Bros. Deluxe.
Does Anyone Knows How can I Fix this Problem so I can use Gameboy and Gameboy Color Multiplayer Using Gameyob Cleary without having any Problem like that "Warining: Link Emulation Sucks."?
Here is my Problem:
![IMG_20240815_134735](https://github.com/user-attachments/assets/5c0ab9b5-b5e1-4c6a-adf2-e3dbfcc32940)
